sudo: required

language: cpp

before_install:
   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
   - sudo apt-get update -qq
   - sudo apt-get install g++-4.9 libhdf5-serial-dev libopenblas-dev liblapack-dev libboost-program-options-dev -y

install:
   - sudo ldconfig
   - sudo updatedb
   - wget http://www.cs.unc.edu/Research/compgeom/gzstream/gzstream.tgz
   - tar xzf gzstream.tgz
   - pushd gzstream && make && popd
   - wget http://sourceforge.net/projects/arma/files/armadillo-6.700.6.tar.gz
   - tar xzf armadillo-6.700.6.tar.gz
   - pushd armadillo-6.700.6 && CXX=/usr/bin/g++-4.9 cmake . && make && sudo make install && popd

#script: CXX=/usr/bin/g++-4.9 make && make test
script: CXX=/usr/bin/g++-4.9 make

after_script:
   - ldd src/seer
   - locate libhdf5
   - make test
